// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: road.proto

#include "road.pb.h"
#include "road.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* Position_method_names[] = {
  "/Position/SendPosition",
};

std::unique_ptr< Position::Stub> Position::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Position::Stub> stub(new Position::Stub(channel));
  return stub;
}

Position::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SendPosition_(Position_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Position::Stub::SendPosition(::grpc::ClientContext* context, const ::PositionRequest& request, ::PositionReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SendPosition_, context, request, response);
}

void Position::Stub::experimental_async::SendPosition(::grpc::ClientContext* context, const ::PositionRequest* request, ::PositionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPosition_, context, request, response, std::move(f));
}

void Position::Stub::experimental_async::SendPosition(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PositionReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SendPosition_, context, request, response, std::move(f));
}

void Position::Stub::experimental_async::SendPosition(::grpc::ClientContext* context, const ::PositionRequest* request, ::PositionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPosition_, context, request, response, reactor);
}

void Position::Stub::experimental_async::SendPosition(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::PositionReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SendPosition_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::PositionReply>* Position::Stub::AsyncSendPositionRaw(::grpc::ClientContext* context, const ::PositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::PositionReply>::Create(channel_.get(), cq, rpcmethod_SendPosition_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::PositionReply>* Position::Stub::PrepareAsyncSendPositionRaw(::grpc::ClientContext* context, const ::PositionRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::PositionReply>::Create(channel_.get(), cq, rpcmethod_SendPosition_, context, request, false);
}

Position::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Position_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Position::Service, ::PositionRequest, ::PositionReply>(
          std::mem_fn(&Position::Service::SendPosition), this)));
}

Position::Service::~Service() {
}

::grpc::Status Position::Service::SendPosition(::grpc::ServerContext* context, const ::PositionRequest* request, ::PositionReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


