// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: road.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_road_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_road_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/timestamp.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_road_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_road_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_road_2eproto;
class PositionReply;
class PositionReplyDefaultTypeInternal;
extern PositionReplyDefaultTypeInternal _PositionReply_default_instance_;
class PositionRequest;
class PositionRequestDefaultTypeInternal;
extern PositionRequestDefaultTypeInternal _PositionRequest_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PositionReply* Arena::CreateMaybeMessage<::PositionReply>(Arena*);
template<> ::PositionRequest* Arena::CreateMaybeMessage<::PositionRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PositionRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PositionRequest) */ {
 public:
  PositionRequest();
  virtual ~PositionRequest();

  PositionRequest(const PositionRequest& from);
  PositionRequest(PositionRequest&& from) noexcept
    : PositionRequest() {
    *this = ::std::move(from);
  }

  inline PositionRequest& operator=(const PositionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionRequest& operator=(PositionRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PositionRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PositionRequest* internal_default_instance() {
    return reinterpret_cast<const PositionRequest*>(
               &_PositionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PositionRequest& a, PositionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PositionRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PositionRequest* New() const final {
    return CreateMaybeMessage<PositionRequest>(nullptr);
  }

  PositionRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PositionRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PositionRequest& from);
  void MergeFrom(const PositionRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PositionRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PositionRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_road_2eproto);
    return ::descriptor_table_road_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientTimeFieldNumber = 7,
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
    kKpFieldNumber = 4,
    kKdFieldNumber = 5,
    kKiFieldNumber = 6,
  };
  // .google.protobuf.Timestamp clientTime = 7;
  bool has_clienttime() const;
  private:
  bool _internal_has_clienttime() const;
  public:
  void clear_clienttime();
  const PROTOBUF_NAMESPACE_ID::Timestamp& clienttime() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* release_clienttime();
  PROTOBUF_NAMESPACE_ID::Timestamp* mutable_clienttime();
  void set_allocated_clienttime(PROTOBUF_NAMESPACE_ID::Timestamp* clienttime);
  private:
  const PROTOBUF_NAMESPACE_ID::Timestamp& _internal_clienttime() const;
  PROTOBUF_NAMESPACE_ID::Timestamp* _internal_mutable_clienttime();
  public:

  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float kp = 4;
  void clear_kp();
  float kp() const;
  void set_kp(float value);
  private:
  float _internal_kp() const;
  void _internal_set_kp(float value);
  public:

  // float kd = 5;
  void clear_kd();
  float kd() const;
  void set_kd(float value);
  private:
  float _internal_kd() const;
  void _internal_set_kd(float value);
  public:

  // float ki = 6;
  void clear_ki();
  float ki() const;
  void set_ki(float value);
  private:
  float _internal_ki() const;
  void _internal_set_ki(float value);
  public:

  // @@protoc_insertion_point(class_scope:PositionRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  PROTOBUF_NAMESPACE_ID::Timestamp* clienttime_;
  float x_;
  float y_;
  float z_;
  float kp_;
  float kd_;
  float ki_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_road_2eproto;
};
// -------------------------------------------------------------------

class PositionReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PositionReply) */ {
 public:
  PositionReply();
  virtual ~PositionReply();

  PositionReply(const PositionReply& from);
  PositionReply(PositionReply&& from) noexcept
    : PositionReply() {
    *this = ::std::move(from);
  }

  inline PositionReply& operator=(const PositionReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline PositionReply& operator=(PositionReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PositionReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PositionReply* internal_default_instance() {
    return reinterpret_cast<const PositionReply*>(
               &_PositionReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PositionReply& a, PositionReply& b) {
    a.Swap(&b);
  }
  inline void Swap(PositionReply* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PositionReply* New() const final {
    return CreateMaybeMessage<PositionReply>(nullptr);
  }

  PositionReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PositionReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PositionReply& from);
  void MergeFrom(const PositionReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PositionReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PositionReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_road_2eproto);
    return ::descriptor_table_road_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPosFieldNumber = 1,
    kServerTimeFieldNumber = 4,
    kDTimeFieldNumber = 3,
    kActuationForceFieldNumber = 2,
    kStandardDeviationFieldNumber = 5,
  };
  // string pos = 1;
  void clear_pos();
  const std::string& pos() const;
  void set_pos(const std::string& value);
  void set_pos(std::string&& value);
  void set_pos(const char* value);
  void set_pos(const char* value, size_t size);
  std::string* mutable_pos();
  std::string* release_pos();
  void set_allocated_pos(std::string* pos);
  private:
  const std::string& _internal_pos() const;
  void _internal_set_pos(const std::string& value);
  std::string* _internal_mutable_pos();
  public:

  // string serverTime = 4;
  void clear_servertime();
  const std::string& servertime() const;
  void set_servertime(const std::string& value);
  void set_servertime(std::string&& value);
  void set_servertime(const char* value);
  void set_servertime(const char* value, size_t size);
  std::string* mutable_servertime();
  std::string* release_servertime();
  void set_allocated_servertime(std::string* servertime);
  private:
  const std::string& _internal_servertime() const;
  void _internal_set_servertime(const std::string& value);
  std::string* _internal_mutable_servertime();
  public:

  // int64 dTime = 3;
  void clear_dtime();
  ::PROTOBUF_NAMESPACE_ID::int64 dtime() const;
  void set_dtime(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_dtime() const;
  void _internal_set_dtime(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // float actuationForce = 2;
  void clear_actuationforce();
  float actuationforce() const;
  void set_actuationforce(float value);
  private:
  float _internal_actuationforce() const;
  void _internal_set_actuationforce(float value);
  public:

  // float standardDeviation = 5;
  void clear_standarddeviation();
  float standarddeviation() const;
  void set_standarddeviation(float value);
  private:
  float _internal_standarddeviation() const;
  void _internal_set_standarddeviation(float value);
  public:

  // @@protoc_insertion_point(class_scope:PositionReply)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr pos_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr servertime_;
  ::PROTOBUF_NAMESPACE_ID::int64 dtime_;
  float actuationforce_;
  float standarddeviation_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_road_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PositionRequest

// float x = 1;
inline void PositionRequest::clear_x() {
  x_ = 0;
}
inline float PositionRequest::_internal_x() const {
  return x_;
}
inline float PositionRequest::x() const {
  // @@protoc_insertion_point(field_get:PositionRequest.x)
  return _internal_x();
}
inline void PositionRequest::_internal_set_x(float value) {
  
  x_ = value;
}
inline void PositionRequest::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:PositionRequest.x)
}

// float y = 2;
inline void PositionRequest::clear_y() {
  y_ = 0;
}
inline float PositionRequest::_internal_y() const {
  return y_;
}
inline float PositionRequest::y() const {
  // @@protoc_insertion_point(field_get:PositionRequest.y)
  return _internal_y();
}
inline void PositionRequest::_internal_set_y(float value) {
  
  y_ = value;
}
inline void PositionRequest::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:PositionRequest.y)
}

// float z = 3;
inline void PositionRequest::clear_z() {
  z_ = 0;
}
inline float PositionRequest::_internal_z() const {
  return z_;
}
inline float PositionRequest::z() const {
  // @@protoc_insertion_point(field_get:PositionRequest.z)
  return _internal_z();
}
inline void PositionRequest::_internal_set_z(float value) {
  
  z_ = value;
}
inline void PositionRequest::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:PositionRequest.z)
}

// float kp = 4;
inline void PositionRequest::clear_kp() {
  kp_ = 0;
}
inline float PositionRequest::_internal_kp() const {
  return kp_;
}
inline float PositionRequest::kp() const {
  // @@protoc_insertion_point(field_get:PositionRequest.kp)
  return _internal_kp();
}
inline void PositionRequest::_internal_set_kp(float value) {
  
  kp_ = value;
}
inline void PositionRequest::set_kp(float value) {
  _internal_set_kp(value);
  // @@protoc_insertion_point(field_set:PositionRequest.kp)
}

// float kd = 5;
inline void PositionRequest::clear_kd() {
  kd_ = 0;
}
inline float PositionRequest::_internal_kd() const {
  return kd_;
}
inline float PositionRequest::kd() const {
  // @@protoc_insertion_point(field_get:PositionRequest.kd)
  return _internal_kd();
}
inline void PositionRequest::_internal_set_kd(float value) {
  
  kd_ = value;
}
inline void PositionRequest::set_kd(float value) {
  _internal_set_kd(value);
  // @@protoc_insertion_point(field_set:PositionRequest.kd)
}

// float ki = 6;
inline void PositionRequest::clear_ki() {
  ki_ = 0;
}
inline float PositionRequest::_internal_ki() const {
  return ki_;
}
inline float PositionRequest::ki() const {
  // @@protoc_insertion_point(field_get:PositionRequest.ki)
  return _internal_ki();
}
inline void PositionRequest::_internal_set_ki(float value) {
  
  ki_ = value;
}
inline void PositionRequest::set_ki(float value) {
  _internal_set_ki(value);
  // @@protoc_insertion_point(field_set:PositionRequest.ki)
}

// .google.protobuf.Timestamp clientTime = 7;
inline bool PositionRequest::_internal_has_clienttime() const {
  return this != internal_default_instance() && clienttime_ != nullptr;
}
inline bool PositionRequest::has_clienttime() const {
  return _internal_has_clienttime();
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& PositionRequest::_internal_clienttime() const {
  const PROTOBUF_NAMESPACE_ID::Timestamp* p = clienttime_;
  return p != nullptr ? *p : *reinterpret_cast<const PROTOBUF_NAMESPACE_ID::Timestamp*>(
      &PROTOBUF_NAMESPACE_ID::_Timestamp_default_instance_);
}
inline const PROTOBUF_NAMESPACE_ID::Timestamp& PositionRequest::clienttime() const {
  // @@protoc_insertion_point(field_get:PositionRequest.clientTime)
  return _internal_clienttime();
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PositionRequest::release_clienttime() {
  // @@protoc_insertion_point(field_release:PositionRequest.clientTime)
  
  PROTOBUF_NAMESPACE_ID::Timestamp* temp = clienttime_;
  clienttime_ = nullptr;
  return temp;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PositionRequest::_internal_mutable_clienttime() {
  
  if (clienttime_ == nullptr) {
    auto* p = CreateMaybeMessage<PROTOBUF_NAMESPACE_ID::Timestamp>(GetArenaNoVirtual());
    clienttime_ = p;
  }
  return clienttime_;
}
inline PROTOBUF_NAMESPACE_ID::Timestamp* PositionRequest::mutable_clienttime() {
  // @@protoc_insertion_point(field_mutable:PositionRequest.clientTime)
  return _internal_mutable_clienttime();
}
inline void PositionRequest::set_allocated_clienttime(PROTOBUF_NAMESPACE_ID::Timestamp* clienttime) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(clienttime_);
  }
  if (clienttime) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(clienttime)->GetArena();
    if (message_arena != submessage_arena) {
      clienttime = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, clienttime, submessage_arena);
    }
    
  } else {
    
  }
  clienttime_ = clienttime;
  // @@protoc_insertion_point(field_set_allocated:PositionRequest.clientTime)
}

// -------------------------------------------------------------------

// PositionReply

// string pos = 1;
inline void PositionReply::clear_pos() {
  pos_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PositionReply::pos() const {
  // @@protoc_insertion_point(field_get:PositionReply.pos)
  return _internal_pos();
}
inline void PositionReply::set_pos(const std::string& value) {
  _internal_set_pos(value);
  // @@protoc_insertion_point(field_set:PositionReply.pos)
}
inline std::string* PositionReply::mutable_pos() {
  // @@protoc_insertion_point(field_mutable:PositionReply.pos)
  return _internal_mutable_pos();
}
inline const std::string& PositionReply::_internal_pos() const {
  return pos_.GetNoArena();
}
inline void PositionReply::_internal_set_pos(const std::string& value) {
  
  pos_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PositionReply::set_pos(std::string&& value) {
  
  pos_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PositionReply.pos)
}
inline void PositionReply::set_pos(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  pos_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PositionReply.pos)
}
inline void PositionReply::set_pos(const char* value, size_t size) {
  
  pos_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PositionReply.pos)
}
inline std::string* PositionReply::_internal_mutable_pos() {
  
  return pos_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PositionReply::release_pos() {
  // @@protoc_insertion_point(field_release:PositionReply.pos)
  
  return pos_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PositionReply::set_allocated_pos(std::string* pos) {
  if (pos != nullptr) {
    
  } else {
    
  }
  pos_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), pos);
  // @@protoc_insertion_point(field_set_allocated:PositionReply.pos)
}

// float actuationForce = 2;
inline void PositionReply::clear_actuationforce() {
  actuationforce_ = 0;
}
inline float PositionReply::_internal_actuationforce() const {
  return actuationforce_;
}
inline float PositionReply::actuationforce() const {
  // @@protoc_insertion_point(field_get:PositionReply.actuationForce)
  return _internal_actuationforce();
}
inline void PositionReply::_internal_set_actuationforce(float value) {
  
  actuationforce_ = value;
}
inline void PositionReply::set_actuationforce(float value) {
  _internal_set_actuationforce(value);
  // @@protoc_insertion_point(field_set:PositionReply.actuationForce)
}

// int64 dTime = 3;
inline void PositionReply::clear_dtime() {
  dtime_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PositionReply::_internal_dtime() const {
  return dtime_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 PositionReply::dtime() const {
  // @@protoc_insertion_point(field_get:PositionReply.dTime)
  return _internal_dtime();
}
inline void PositionReply::_internal_set_dtime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  dtime_ = value;
}
inline void PositionReply::set_dtime(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_dtime(value);
  // @@protoc_insertion_point(field_set:PositionReply.dTime)
}

// string serverTime = 4;
inline void PositionReply::clear_servertime() {
  servertime_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& PositionReply::servertime() const {
  // @@protoc_insertion_point(field_get:PositionReply.serverTime)
  return _internal_servertime();
}
inline void PositionReply::set_servertime(const std::string& value) {
  _internal_set_servertime(value);
  // @@protoc_insertion_point(field_set:PositionReply.serverTime)
}
inline std::string* PositionReply::mutable_servertime() {
  // @@protoc_insertion_point(field_mutable:PositionReply.serverTime)
  return _internal_mutable_servertime();
}
inline const std::string& PositionReply::_internal_servertime() const {
  return servertime_.GetNoArena();
}
inline void PositionReply::_internal_set_servertime(const std::string& value) {
  
  servertime_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PositionReply::set_servertime(std::string&& value) {
  
  servertime_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PositionReply.serverTime)
}
inline void PositionReply::set_servertime(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  servertime_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PositionReply.serverTime)
}
inline void PositionReply::set_servertime(const char* value, size_t size) {
  
  servertime_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PositionReply.serverTime)
}
inline std::string* PositionReply::_internal_mutable_servertime() {
  
  return servertime_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PositionReply::release_servertime() {
  // @@protoc_insertion_point(field_release:PositionReply.serverTime)
  
  return servertime_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PositionReply::set_allocated_servertime(std::string* servertime) {
  if (servertime != nullptr) {
    
  } else {
    
  }
  servertime_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), servertime);
  // @@protoc_insertion_point(field_set_allocated:PositionReply.serverTime)
}

// float standardDeviation = 5;
inline void PositionReply::clear_standarddeviation() {
  standarddeviation_ = 0;
}
inline float PositionReply::_internal_standarddeviation() const {
  return standarddeviation_;
}
inline float PositionReply::standarddeviation() const {
  // @@protoc_insertion_point(field_get:PositionReply.standardDeviation)
  return _internal_standarddeviation();
}
inline void PositionReply::_internal_set_standarddeviation(float value) {
  
  standarddeviation_ = value;
}
inline void PositionReply::set_standarddeviation(float value) {
  _internal_set_standarddeviation(value);
  // @@protoc_insertion_point(field_set:PositionReply.standardDeviation)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_road_2eproto
